import type { ChecklistItem } from "@/types/expert";

const EURLEX = "https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=OJ:L_202401689";
const GDPR = "https://gdpr-info.eu";

export const AI_ACT_CHECKLIST: ChecklistItem[] = [
  // Prohibited uses
  {
    id: "aa-prohibited",
    article: "Art. 5",
    title: "Prohibited use check",
    description: "Confirm the system does not fall under any prohibited AI practice (social scoring, subliminal manipulation, real-time biometric ID in public spaces, etc.).",
    category: "Prohibited Practices",
    mandatory: true,
    url: `${EURLEX}#art_5`,
  },
  // Classification
  {
    id: "aa-classification",
    article: "Art. 6",
    title: "Risk classification documented",
    description: "Determine and document whether the system is high-risk under Art. 6 and Annex III. Record the reasoning.",
    category: "Classification",
    mandatory: true,
    url: `${EURLEX}#art_6`,
  },
  {
    id: "aa-literacy",
    article: "Art. 4",
    title: "AI literacy training",
    description: "Ensure staff and users who operate AI systems have sufficient AI literacy appropriate to their role.",
    category: "Classification",
    mandatory: true,
    url: `${EURLEX}#art_4`,
  },
  // High-risk obligations
  {
    id: "aa-risk-mgmt",
    article: "Art. 9",
    title: "Risk management system",
    description: "Establish, implement, document, and maintain a risk management system throughout the lifecycle of the high-risk AI system.",
    category: "High-Risk Obligations",
    mandatory: true,
    url: `${EURLEX}#art_9`,
  },
  {
    id: "aa-data-gov",
    article: "Art. 10",
    title: "Data governance policy",
    description: "Implement data governance practices: training, validation, and testing datasets must be relevant, representative, free of errors, and complete.",
    category: "High-Risk Obligations",
    mandatory: true,
    url: `${EURLEX}#art_10`,
  },
  {
    id: "aa-tech-doc",
    article: "Art. 11",
    title: "Technical documentation",
    description: "Prepare and maintain technical documentation (Annex IV) before placing the system on the market. Must cover design, development, testing, and monitoring.",
    category: "High-Risk Obligations",
    mandatory: true,
    url: `${EURLEX}#art_11`,
  },
  {
    id: "aa-logging",
    article: "Art. 12",
    title: "Automatic logging enabled",
    description: "Enable automatic recording of events (logs) to the extent necessary for post-market monitoring and incident analysis.",
    category: "High-Risk Obligations",
    mandatory: true,
    url: `${EURLEX}#art_12`,
  },
  {
    id: "aa-transparency",
    article: "Art. 13",
    title: "Transparency documentation for deployers",
    description: "Provide deployers with clear instructions on intended purpose, performance metrics, limitations, human oversight measures, and how to interpret outputs.",
    category: "High-Risk Obligations",
    mandatory: true,
    url: `${EURLEX}#art_13`,
  },
  {
    id: "aa-human-oversight",
    article: "Art. 14",
    title: "Human oversight mechanisms",
    description: "Design the system to allow natural persons to effectively oversee and intervene. Define who is responsible and how they can stop, override, or correct the system.",
    category: "High-Risk Obligations",
    mandatory: true,
    url: `${EURLEX}#art_14`,
  },
  {
    id: "aa-accuracy",
    article: "Art. 15",
    title: "Accuracy, robustness & cybersecurity",
    description: "Achieve appropriate levels of accuracy. Implement measures for resilience against errors, faults, and adversarial attacks. Document performance metrics.",
    category: "High-Risk Obligations",
    mandatory: true,
    url: `${EURLEX}#art_15`,
  },
  // Conformity & registration
  {
    id: "aa-conformity",
    article: "Art. 43",
    title: "Conformity assessment completed",
    description: "Conduct (or commission) a conformity assessment before placing the system on the market. Third-party assessment required for certain high-risk categories.",
    category: "Conformity & Registration",
    mandatory: true,
    url: `${EURLEX}#art_43`,
  },
  {
    id: "aa-declaration",
    article: "Art. 49",
    title: "EU Declaration of Conformity signed",
    description: "Draw up and sign an EU Declaration of Conformity, confirming the system meets all applicable requirements of the AI Act.",
    category: "Conformity & Registration",
    mandatory: true,
    url: `${EURLEX}#art_49`,
  },
  {
    id: "aa-ce-marking",
    article: "Art. 48",
    title: "CE marking applied",
    description: "Affix CE marking to the AI system (or its documentation) to indicate conformity with the AI Act requirements.",
    category: "Conformity & Registration",
    mandatory: true,
    url: `${EURLEX}#art_48`,
  },
  // Transparency for limited risk
  {
    id: "aa-chatbot-disclosure",
    article: "Art. 50",
    title: "AI disclosure to end users",
    description: "Inform users they are interacting with an AI system (chatbots, synthetic media). AI-generated content must be labelled as such.",
    category: "Transparency Obligations",
    mandatory: true,
    url: `${EURLEX}#art_50`,
  },
  // GPAI
  {
    id: "aa-gpai-policy",
    article: "Art. 53",
    title: "GPAI model — copyright & training data policy",
    description: "If providing a general-purpose AI model: document training data, respect copyright opt-outs, and publish a summary of training content.",
    category: "GPAI Obligations",
    mandatory: false,
    url: `${EURLEX}#art_53`,
  },
  {
    id: "aa-codes-conduct",
    article: "Art. 95",
    title: "Voluntary code of conduct adopted",
    description: "For minimal-risk systems, consider adopting a voluntary code of conduct to demonstrate responsible AI practices.",
    category: "Voluntary",
    mandatory: false,
    url: `${EURLEX}#art_95`,
  },
];

export const GDPR_CHECKLIST: ChecklistItem[] = [
  // Lawful basis
  {
    id: "gdpr-lawful-basis",
    article: "Art. 6",
    title: "Lawful basis identified and documented",
    description: "Document the lawful basis for each processing activity. If relying on legitimate interests, conduct a Legitimate Interest Assessment (LIA).",
    category: "Lawful Basis",
    mandatory: true,
    url: `${GDPR}/art-6-gdpr/`,
  },
  {
    id: "gdpr-consent",
    article: "Art. 7",
    title: "Consent mechanism compliant",
    description: "If relying on consent: it must be freely given, specific, informed, and unambiguous. Withdrawal must be as easy as giving consent. Keep consent records.",
    category: "Lawful Basis",
    mandatory: false,
    url: `${GDPR}/art-7-gdpr/`,
  },
  {
    id: "gdpr-special-cat",
    article: "Art. 9",
    title: "Special category data grounds documented",
    description: "If processing health, biometric, racial/ethnic, political, religious, genetic, or sexual orientation data — document the specific Art. 9(2) ground applied.",
    category: "Lawful Basis",
    mandatory: true,
    url: `${GDPR}/art-9-gdpr/`,
  },
  // Transparency
  {
    id: "gdpr-privacy-notice",
    article: "Art. 13 / 14",
    title: "Privacy notice published",
    description: "Publish a clear, accessible privacy notice covering: identity of controller, purposes and legal basis, retention periods, data subject rights, and contact details.",
    category: "Transparency",
    mandatory: true,
    url: `${GDPR}/art-13-gdpr/`,
  },
  // Data subject rights
  {
    id: "gdpr-access",
    article: "Art. 15",
    title: "Right of access procedure",
    description: "Have a process to respond to access requests within 1 month. Provide copy of data, purposes, recipients, retention, and rights information.",
    category: "Data Subject Rights",
    mandatory: true,
    url: `${GDPR}/art-15-gdpr/`,
  },
  {
    id: "gdpr-rectification",
    article: "Art. 16",
    title: "Right to rectification",
    description: "Enable data subjects to correct inaccurate personal data without undue delay.",
    category: "Data Subject Rights",
    mandatory: true,
    url: `${GDPR}/art-16-gdpr/`,
  },
  {
    id: "gdpr-erasure",
    article: "Art. 17",
    title: "Right to erasure (right to be forgotten)",
    description: "Establish a process to delete personal data on request where no legitimate grounds for retention remain.",
    category: "Data Subject Rights",
    mandatory: true,
    url: `${GDPR}/art-17-gdpr/`,
  },
  {
    id: "gdpr-portability",
    article: "Art. 20",
    title: "Right to data portability",
    description: "Provide personal data in a structured, machine-readable format on request (applies where processing is based on consent or contract).",
    category: "Data Subject Rights",
    mandatory: true,
    url: `${GDPR}/art-20-gdpr/`,
  },
  {
    id: "gdpr-automated",
    article: "Art. 22",
    title: "Automated decision-making safeguards",
    description: "If making solely automated decisions with legal or significant effects: ensure human review option, right to contest, and clear disclosure to data subjects.",
    category: "Data Subject Rights",
    mandatory: true,
    url: `${GDPR}/art-22-gdpr/`,
  },
  // Controller obligations
  {
    id: "gdpr-privacy-by-design",
    article: "Art. 25",
    title: "Data protection by design and by default",
    description: "Implement technical and organisational measures to embed data protection into processing from design. Default settings must be privacy-friendly.",
    category: "Controller Obligations",
    mandatory: true,
    url: `${GDPR}/art-25-gdpr/`,
  },
  {
    id: "gdpr-dpa",
    article: "Art. 28",
    title: "Data processing agreements in place",
    description: "Sign DPAs with all processors (cloud providers, SaaS tools, analytics platforms) covering subject matter, duration, and obligations.",
    category: "Controller Obligations",
    mandatory: true,
    url: `${GDPR}/art-28-gdpr/`,
  },
  {
    id: "gdpr-ropa",
    article: "Art. 30",
    title: "Records of processing activities (RoPA)",
    description: "Maintain a written record of all processing activities with purposes, categories of data and subjects, recipients, retention periods, and security measures.",
    category: "Controller Obligations",
    mandatory: true,
    url: `${GDPR}/art-30-gdpr/`,
  },
  {
    id: "gdpr-security",
    article: "Art. 32",
    title: "Security of processing documented",
    description: "Implement and document appropriate technical and organisational security measures (encryption, access controls, pseudonymisation, regular testing).",
    category: "Controller Obligations",
    mandatory: true,
    url: `${GDPR}/art-32-gdpr/`,
  },
  {
    id: "gdpr-breach",
    article: "Art. 33 / 34",
    title: "Breach notification procedure",
    description: "Have a procedure to detect, assess, and notify the supervisory authority within 72 hours of a breach. Notify data subjects if high risk.",
    category: "Controller Obligations",
    mandatory: true,
    url: `${GDPR}/art-33-gdpr/`,
  },
  {
    id: "gdpr-dpia",
    article: "Art. 35",
    title: "DPIA conducted (if required)",
    description: "Conduct a Data Protection Impact Assessment for high-risk processing (new technologies, large-scale special category data, systematic monitoring).",
    category: "Risk & Oversight",
    mandatory: false,
    url: `${GDPR}/art-35-gdpr/`,
  },
  {
    id: "gdpr-dpo",
    article: "Art. 37",
    title: "DPO appointed (if required)",
    description: "Appoint a Data Protection Officer if: public authority, large-scale systematic monitoring, or large-scale special category data processing. Publish DPO contact.",
    category: "Risk & Oversight",
    mandatory: false,
    url: `${GDPR}/art-37-gdpr/`,
  },
  {
    id: "gdpr-transfers",
    article: "Art. 44–46",
    title: "International transfer safeguards",
    description: "If transferring personal data outside the EEA: rely on an adequacy decision, Standard Contractual Clauses, or Binding Corporate Rules. Document the transfer mechanism.",
    category: "International Transfers",
    mandatory: false,
    url: `${GDPR}/art-44-gdpr/`,
  },
  {
    id: "gdpr-retention",
    article: "Art. 5(1)(e)",
    title: "Data retention policy",
    description: "Define and enforce retention periods for all categories of personal data. Data must not be kept longer than necessary for the stated purpose.",
    category: "Controller Obligations",
    mandatory: true,
    url: `${GDPR}/art-5-gdpr/`,
  },
];
